apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: karpenter.k8s.aws
      version: v1beta1
      kind: EC2NodeClass
      name: default
    patch: |-
      - op: replace
        path: /spec/amiFamily
        value: AL2023
  - target:
      group: karpenter.k8s.aws
      version: v1beta1
      kind: EC2NodeClass
      name: pd-only
    patch: |-
      - op: replace
        path: /spec/amiFamily
        value: AL2023
  - target:
      group: karpenter.k8s.aws
      version: v1beta1
      kind: EC2NodeClass
      name: pgo-only
    patch: |-
      - op: replace
        path: /spec/amiFamily
        value: AL2023