apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/1/env/-
        value:
          name: SIGSCI_MAX_PROCS
          value: "100%"
    target:
      kind: Deployment
      name: nginx-ingress-controller
      namespace: ingress-nginx-public